name: Build iOS Library

on: push

jobs:
  build:
    name: Build for aarch64-apple-ios
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build for aarch64-apple-ios
        run: cargo build --target aarch64-apple-ios --lib --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chums-proxy
          path: target/aarch64-apple-ios/release/libchums_proxy.*

  release:
    name: Create GitHub Release
    runs-on: [self-hosted, macOS, ARM64]
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chums-proxy
          path: artifacts

      - name: Generate timestamp
        id: meta
        run: |
          timestamp="$(date +'%Y-%m-%dT%H-%M-%S')"
          echo "tag_name=v$timestamp" >> "$GITHUB_OUTPUT"
          echo "release_name=Release ${timestamp//T/ }" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.meta.outputs.release_name }}
          tag_name: ${{ steps.meta.outputs.tag_name }}
          files: artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
