name: Build iOS Library

on: push

jobs:
  build-ios:
    name: Build for aarch64-apple-ios
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build for aarch64-apple-ios
        run: cargo build --target aarch64-apple-ios --lib --release
