name: Build iOS Library

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build for aarch64-apple-ios
    runs-on: [self-hosted, chums-macos-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build for aarch64-apple-ios
        run: cargo build --target aarch64-apple-ios --lib --release
